# Site settings
title: Zhiwen Shao (邵志文)
description:
  en: "* Corresponding author. † Equal contribution. This is an academic website for Zhiwen Shao to share his experiences, projects, publications, and posts. Zhiwen Shao is now a Ph.D. candidate in the Department of Computer Science and Engineering, Shanghai Jiao Tong University, China, advised by Prof. Lizhuang Ma. His research interests lie in the field of Face Analysis and Deep Learning, particularly in Face Alignment and Facial Expression Recognition. "
  cn: "这是邵志文的个人学术主页，用于分享他的个人经历，项目，学术论文，博客。"
keywords:
  en: "Zhiwen Shao,Publications,Posts,Research,Face Analysis,Deep Learning,Face Alignment, Facial Expression Recognition"
  cn: "邵志文,学术论文,博客,研究,人脸分析,深度学习,人脸配准,人脸表情识别"
background: /images/background/background-tech.jpg
deep_background: /images/background/background-tech.jpg

baseurl: ""
# the subpath of your site, e.g. /blog/
url: "https://zhiwenshao.github.io/"
# the base hostname & protocol for your sit

# Paginationœ
paginate: 6
paginate_path: "/posts/page/:num/"

# Build settings
markdown: kramdown

# permalink setting
permalink: pretty
# highlighter: rouge
highlighter: rouge

# Social media link for the site
social:
  google_scholar: citations?user=YPIrQcQAAAAJ&hl
  #twitter:    Hexiang_Hu
  github:     ZhiwenShao
  #facebook:   Hu.Hexiang
  linkedin:   zhiwen-shao-3586bb135
  #rss:        /feed.xml

#google_analytics_token: "UA-60071442-1"
#google_tags_token: "GTM-K5ZTMW"


# customized document resources
collections:
  projects:
    output: true

scss:
  sass_dir: _scss
  style: :compressed

gems:
  ['jekyll-paginate', 'jekyll/scholar', 'jekyll-sitemap']
